
## OpenNMT-py config for SMILES Molecular Transformer baseline

save_data: smiles_run/data
src_vocab: smiles_run/smiles.vocab.src
tgt_vocab: smiles_run/smiles.vocab.src
overwrite: true
share_vocab: true

data:
    corpus-1:
        path_src: USPTO_SMILES_preprocessed/src-train.txt
        path_tgt: USPTO_SMILES_preprocessed/tgt-train.txt
    valid:
        path_src: USPTO_SMILES_preprocessed/src-val.txt
        path_tgt: USPTO_SMILES_preprocessed/tgt-val.txt

world_size: 1
gpu_ranks: [0]
save_model: smiles_run/model
save_checkpoint_steps: 5000
keep_checkpoint: 5
train_steps: 400000
valid_steps: 10000
report_every: 100
tensorboard: true
tensorboard_log_dir: smiles_log_dir
